set(PRECOMPILED_DIR "${PROJECT_SOURCE_DIR}/precompiled_libraries")

if (SEMBA_FDTD_ENABLE_MTLN)
	if (${CMAKE_SYSTEM_NAME} STREQUAL "Linux")
		if (${CMAKE_Fortran_COMPILER_ID} STREQUAL "GNU")
			set(LAPACK_DIR "${PRECOMPILED_DIR}/linux-gcc/lapack/")
			set(LAPACK_LIB ${LAPACK_DIR}liblapack.a)
			set(BLAS_LIB ${LAPACK_DIR}libblas.a)
		elseif (${CMAKE_Fortran_COMPILER_ID} STREQUAL "NVHPC")
			set(LAPACK_DIR "/opt/nvidia/hpc_sdk/Linux_x86_64/24.5/compilers/lib/")
			set(LAPACK_LIB ${LAPACK_DIR}liblapack.a)
			set(BLAS_LIB ${LAPACK_DIR}libblas.a)
		elseif (${CMAKE_Fortran_COMPILER_ID} STREQUAL "IntelLLVM")
			set(LAPACK_DIR "${PRECOMPILED_DIR}/linux-intelLLVM/lapack/")
			set(LAPACK_LIB ${LAPACK_DIR}liblapack.a)
			set(BLAS_LIB ${LAPACK_DIR}libblas.a)
		endif()
	elseif(${CMAKE_SYSTEM_NAME} STREQUAL "Windows")
		if(${CMAKE_Fortran_COMPILER_ID} STREQUAL "IntelLLVM")
			set(LAPACK_DIR "${PRECOMPILED_DIR}/windows-intelLLVM/lapack/")
			set(LAPACK_LIB ${LAPACK_DIR}liblapack.lib)
			set(BLAS_LIB ${LAPACK_DIR}libblas.lib)
		endif()
	endif()
	if(NOT LAPACK_DIR)
		message(FATAL_ERROR "lapack libraries for this platform and/or compiler have not been found.")
	endif()
	MESSAGE(STATUS "Using lapack libraries at: " ${LAPACK_DIR})
endif()

if (SEMBA_FDTD_ENABLE_HDF)
	add_definitions(-DCompileWithHDF)
	if (NOT HDF5_FOUND)
		if (NOT HDF5_ROOT)
			if (${CMAKE_SYSTEM_NAME} STREQUAL "Linux")
				if(CMAKE_Fortran_COMPILER_ID STREQUAL "GNU" OR ${CMAKE_Fortran_COMPILER_ID} STREQUAL "NVHPC")
					# System libraries. Install with sudo apt install libhdf5-dev hdf5-tools
				elseif(${CMAKE_Fortran_COMPILER_ID} STREQUAL "IntelLLVM")
					set(HDF5_DIR ${PRECOMPILED_DIR}/linux-intel/hdf5/cmake/)
				endif()
			elseif(${CMAKE_SYSTEM_NAME} STREQUAL "Windows")
				if(${CMAKE_Fortran_COMPILER_ID} STREQUAL "IntelLLVM")
					set(HDF5_DIR ${PRECOMPILED_DIR}/windows-intel/hdf5/cmake/)
				endif()
			endif()
		endif()
		if(NOT DEFINED HDF5_USE_STATIC_LIBRARIES AND NOT SEMBA_FDTD_ENABLE_MPI)
			set(HDF5_USE_STATIC_LIBRARIES TRUE)
		endif()
		find_package(HDF5 REQUIRED COMPONENTS Fortran HL)
	endif()
	if (HDF5_FOUND)
		message(STATUS "hdf5 found at: ${HDF5_Fortran_INCLUDE_DIRS}")
	else()
		message(FATAL_ERROR "hdf5 libraries for this platform and/or compiler have not been found.")
	endif()
endif()

if (SEMBA_FDTD_ENABLE_MPI)
	add_definitions(-DCompileWithMPI)
	find_package(MPI REQUIRED COMPONENTS Fortran)
	if (MPI_FOUND)
		message(STATUS "MPI found at: ${MPI_Fortran_INCLUDE_DIRS}")
	endif()

	add_definitions(${MPI_Fortran_COMPILE_OPTIONS})
	include_directories(${MPI_Fortran_INCLUDE_DIRS})
	link_directories(${MPI_Fortran_LIBRARIES})
	add_compile_options (${MPI_Fortran_COMPILER_FLAGS})
endif()

set(SEMBA_FDTD_HAVE_PARALLEL_HDF5_FORTRAN FALSE)
if (SEMBA_FDTD_ENABLE_MPI AND SEMBA_FDTD_ENABLE_HDF AND HDF5_IS_PARALLEL)
	include(CMakePushCheckState)
	include(CheckFortranSourceCompiles)
	cmake_push_check_state(RESET)
	set(CMAKE_REQUIRED_INCLUDES ${HDF5_Fortran_INCLUDE_DIRS} ${MPI_Fortran_INCLUDE_DIRS})
	set(CMAKE_REQUIRED_LIBRARIES ${HDF5_Fortran_LIBRARIES} ${HDF5_LIBRARIES} MPI::MPI_Fortran)
	check_fortran_source_compiles([=[
program parallel_hdf5_probe
  use hdf5
  use mpi
  implicit none
  integer :: error
  integer(HID_T) :: file_access_plist, transfer_plist

  call h5open_f(error)
  call h5pcreate_f(H5P_FILE_ACCESS_F, file_access_plist, error)
  call h5pset_fapl_mpio_f(file_access_plist, MPI_COMM_WORLD, MPI_INFO_NULL, error)
  call h5pcreate_f(H5P_DATASET_XFER_F, transfer_plist, error)
  call h5pset_dxpl_mpio_f(transfer_plist, H5FD_MPIO_COLLECTIVE_F, error)
  call h5pclose_f(transfer_plist, error)
  call h5pclose_f(file_access_plist, error)
  call h5close_f(error)
end program parallel_hdf5_probe
]=] SEMBA_FDTD_PARALLEL_HDF5_PROBE_WORKS SRC_EXT F90)
	cmake_pop_check_state()

	if (NOT SEMBA_FDTD_PARALLEL_HDF5_PROBE_WORKS)
		message(FATAL_ERROR
			"The selected HDF5 and MPI libraries cannot compile and link the parallel HDF5 Fortran API.")
	endif()
	set(SEMBA_FDTD_HAVE_PARALLEL_HDF5_FORTRAN TRUE)
	message(STATUS "Parallel HDF5 Fortran API is available")
elseif(SEMBA_FDTD_ENABLE_MPI AND SEMBA_FDTD_ENABLE_HDF)
	message(STATUS "MPI build is using serial HDF5; the parallel HDF5 movie backend is unavailable")
endif()
