# Portable CUDA setup for SEMBA_FDTD_ENABLE_CUDA.
# Included from the top-level CMakeLists.txt (same directory as project()).
#
# Locates nvcc from the environment or a local toolkit install, picks a host
# compiler that the toolkit can drive, and targets the GPUs on this machine
# unless the user already set CMAKE_CUDA_ARCHITECTURES / CUDA_ARCH.
# No toolkit path or sm_XX is hardcoded.

if(CMAKE_VERSION VERSION_LESS 3.18)
	message(FATAL_ERROR "SEMBA_FDTD_ENABLE_CUDA requires CMake 3.18 or newer (found ${CMAKE_VERSION})")
endif()

function(semba_fdtd_cuda_nvcc_version nvcc outvar)
	execute_process(
		COMMAND "${nvcc}" --version
		OUTPUT_VARIABLE _out
		ERROR_VARIABLE _err
		RESULT_VARIABLE _rc
		OUTPUT_STRIP_TRAILING_WHITESPACE
	)
	if(NOT _rc EQUAL 0)
		message(FATAL_ERROR "Failed to run '${nvcc} --version': ${_err}")
	endif()
	if(_out MATCHES "release ([0-9]+\\.[0-9]+)")
		set(${outvar} "${CMAKE_MATCH_1}" PARENT_SCOPE)
	else()
		message(FATAL_ERROR "Could not parse CUDA version from: ${_out}")
	endif()
endfunction()

function(semba_fdtd_cuda_max_host_gcc cuda_ver outvar)
	# Conservative upper bounds from NVIDIA's documented host-compiler support.
	if(cuda_ver VERSION_GREATER_EQUAL 13.0)
		set(${outvar} 14 PARENT_SCOPE)
	elseif(cuda_ver VERSION_GREATER_EQUAL 12.4)
		set(${outvar} 13 PARENT_SCOPE)
	elseif(cuda_ver VERSION_GREATER_EQUAL 12.0)
		set(${outvar} 12 PARENT_SCOPE)
	elseif(cuda_ver VERSION_GREATER_EQUAL 11.4)
		set(${outvar} 11 PARENT_SCOPE)
	elseif(cuda_ver VERSION_GREATER_EQUAL 11.0)
		set(${outvar} 10 PARENT_SCOPE)
	else()
		set(${outvar} 9 PARENT_SCOPE)
	endif()
endfunction()

function(semba_fdtd_cuda_min_toolkit_for_arch arch outvar)
	if(arch GREATER_EQUAL 120)
		set(${outvar} 12.8 PARENT_SCOPE)
	elseif(arch GREATER_EQUAL 100)
		set(${outvar} 12.8 PARENT_SCOPE)
	elseif(arch GREATER_EQUAL 90)
		set(${outvar} 11.8 PARENT_SCOPE)
	elseif(arch GREATER_EQUAL 89)
		set(${outvar} 11.8 PARENT_SCOPE)
	elseif(arch GREATER_EQUAL 87)
		set(${outvar} 11.4 PARENT_SCOPE)
	elseif(arch GREATER_EQUAL 86)
		set(${outvar} 11.1 PARENT_SCOPE)
	elseif(arch GREATER_EQUAL 80)
		set(${outvar} 11.0 PARENT_SCOPE)
	else()
		set(${outvar} 10.0 PARENT_SCOPE)
	endif()
endfunction()

function(semba_fdtd_cuda_arch_supported arch cuda_ver outvar)
	semba_fdtd_cuda_min_toolkit_for_arch("${arch}" _min)
	if(cuda_ver VERSION_LESS _min)
		set(${outvar} FALSE PARENT_SCOPE)
		return()
	endif()
	if(cuda_ver VERSION_GREATER_EQUAL 13.0 AND arch LESS 75)
		set(${outvar} FALSE PARENT_SCOPE)
		return()
	endif()
	set(${outvar} TRUE PARENT_SCOPE)
endfunction()

function(semba_fdtd_cuda_filter_archs archs cuda_ver outvar)
	set(_kept)
	foreach(_arch IN LISTS archs)
		if(_arch STREQUAL "native" OR _arch STREQUAL "all" OR _arch STREQUAL "all-major")
			list(APPEND _kept "${_arch}")
			continue()
		endif()
		string(REGEX REPLACE "-(real|virtual)$" "" _arch_num "${_arch}")
		semba_fdtd_cuda_arch_supported("${_arch_num}" "${cuda_ver}" _ok)
		if(_ok)
			list(APPEND _kept "${_arch}")
		else()
			message(STATUS "FDTD CUDA: skipping sm_${_arch} (toolkit ${cuda_ver} cannot target it)")
		endif()
	endforeach()
	list(REMOVE_DUPLICATES _kept)
	set(${outvar} "${_kept}" PARENT_SCOPE)
endfunction()

function(semba_fdtd_cuda_find_nvcc outvar)
	set(_nvcc "")
	if(CMAKE_CUDA_COMPILER)
		if(EXISTS "${CMAKE_CUDA_COMPILER}")
			set(_nvcc "${CMAKE_CUDA_COMPILER}")
		else()
			find_program(_nvcc_from_cache NAMES "${CMAKE_CUDA_COMPILER}")
			if(_nvcc_from_cache)
				set(_nvcc "${_nvcc_from_cache}")
			else()
				set(_nvcc "${CMAKE_CUDA_COMPILER}")
			endif()
		endif()
	endif()

	if(NOT _nvcc)
		foreach(_root IN ITEMS
			"${CUDAToolkit_ROOT}"
			"$ENV{CUDAToolkit_ROOT}"
			"$ENV{CUDA_HOME}"
			"$ENV{CUDA_PATH}")
			if(_root)
				if(EXISTS "${_root}/bin/nvcc")
					set(_nvcc "${_root}/bin/nvcc")
					break()
				endif()
				if(EXISTS "${_root}/bin/nvcc.exe")
					set(_nvcc "${_root}/bin/nvcc.exe")
					break()
				endif()
			endif()
		endforeach()
	endif()

	if(NOT _nvcc)
		find_program(_nvcc_path NAMES nvcc nvcc.exe)
		if(_nvcc_path)
			set(_nvcc "${_nvcc_path}")
		endif()
	endif()

	if(NOT _nvcc AND EXISTS "/usr/local/cuda/bin/nvcc")
		set(_nvcc "/usr/local/cuda/bin/nvcc")
	endif()

	if(NOT _nvcc)
		set(_candidates)
		file(GLOB _linux_nvccs "/usr/local/cuda-*/bin/nvcc")
		list(APPEND _candidates ${_linux_nvccs})
		file(GLOB _win_nvccs "C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v*/bin/nvcc.exe")
		list(APPEND _candidates ${_win_nvccs})
		if(_candidates)
			set(_versions)
			foreach(_p IN LISTS _candidates)
				if(_p MATCHES "cuda-([0-9]+\\.[0-9]+)")
					list(APPEND _versions "${CMAKE_MATCH_1}")
				elseif(_p MATCHES "/v([0-9]+\\.[0-9]+)/")
					list(APPEND _versions "${CMAKE_MATCH_1}")
				endif()
			endforeach()
			if(_versions)
				list(SORT _versions COMPARE NATURAL ORDER DESCENDING)
				list(GET _versions 0 _best)
				foreach(_p IN LISTS _candidates)
					if(_p MATCHES "cuda-${_best}/" OR _p MATCHES "/v${_best}/")
						set(_nvcc "${_p}")
						break()
					endif()
				endforeach()
			endif()
		endif()
	endif()

	if(NOT _nvcc)
		message(FATAL_ERROR
			"SEMBA_FDTD_ENABLE_CUDA=ON but nvcc was not found. Set CMAKE_CUDA_COMPILER, "
			"CUDAToolkit_ROOT, CUDA_HOME, or CUDA_PATH to a CUDA toolkit install.")
	endif()
	if(NOT EXISTS "${_nvcc}")
		message(FATAL_ERROR "CMAKE_CUDA_COMPILER does not exist: ${_nvcc}")
	endif()
	set(${outvar} "${_nvcc}" PARENT_SCOPE)
endfunction()

function(semba_fdtd_cuda_gcc_major compiler outvar)
	execute_process(
		COMMAND "${compiler}" -dumpfullversion -dumpversion
		OUTPUT_VARIABLE _ver
		ERROR_QUIET
		OUTPUT_STRIP_TRAILING_WHITESPACE
	)
	if(_ver MATCHES "^([0-9]+)")
		set(${outvar} "${CMAKE_MATCH_1}" PARENT_SCOPE)
	else()
		set(${outvar} "" PARENT_SCOPE)
	endif()
endfunction()

function(semba_fdtd_cuda_pick_host_compiler cuda_ver outvar)
	if(WIN32)
		set(${outvar} "" PARENT_SCOPE)
		return()
	endif()

	if(CMAKE_CUDA_HOST_COMPILER)
		set(${outvar} "${CMAKE_CUDA_HOST_COMPILER}" PARENT_SCOPE)
		return()
	endif()
	if(DEFINED ENV{CUDAHOSTCXX} AND NOT "$ENV{CUDAHOSTCXX}" STREQUAL "")
		set(${outvar} "$ENV{CUDAHOSTCXX}" PARENT_SCOPE)
		return()
	endif()

	semba_fdtd_cuda_max_host_gcc("${cuda_ver}" _max_gcc)

	set(_preferred)
	if(CMAKE_CXX_COMPILER)
		list(APPEND _preferred "${CMAKE_CXX_COMPILER}")
	endif()
	find_program(_gxx NAMES g++ c++)
	if(_gxx)
		list(APPEND _preferred "${_gxx}")
	endif()

	foreach(_cand IN LISTS _preferred)
		semba_fdtd_cuda_gcc_major("${_cand}" _maj)
		if(_maj AND NOT _maj GREATER _max_gcc)
			set(${outvar} "${_cand}" PARENT_SCOPE)
			return()
		endif()
	endforeach()

	set(_n "${_max_gcc}")
	while(_n GREATER_EQUAL 9)
		unset(_gxx_n CACHE)
		find_program(_gxx_n NAMES g++-${_n})
		if(_gxx_n)
			set(${outvar} "${_gxx_n}" PARENT_SCOPE)
			return()
		endif()
		math(EXPR _n "${_n} - 1")
	endwhile()

	if(_gxx)
		message(WARNING
			"FDTD CUDA: host compiler ${_gxx} may be newer than CUDA ${cuda_ver} supports "
			"(max GCC ${_max_gcc}). Set CMAKE_CUDA_HOST_COMPILER to a supported g++.")
		set(${outvar} "${_gxx}" PARENT_SCOPE)
		return()
	endif()

	set(${outvar} "" PARENT_SCOPE)
endfunction()

function(semba_fdtd_cuda_detect_gpu_archs outvar)
	set(_archs)
	find_program(_nvidia_smi NAMES nvidia-smi)
	if(_nvidia_smi)
		execute_process(
			COMMAND "${_nvidia_smi}" --query-gpu=compute_cap --format=csv,noheader
			OUTPUT_VARIABLE _caps
			ERROR_QUIET
			RESULT_VARIABLE _rc
			OUTPUT_STRIP_TRAILING_WHITESPACE
		)
		if(_rc EQUAL 0 AND _caps)
			string(REPLACE "\n" ";" _cap_list "${_caps}")
			foreach(_cap IN LISTS _cap_list)
				string(STRIP "${_cap}" _cap)
				if(_cap MATCHES "^[0-9]+\\.[0-9]+$")
					string(REPLACE "." "" _arch "${_cap}")
					list(APPEND _archs "${_arch}")
				endif()
			endforeach()
			list(REMOVE_DUPLICATES _archs)
		endif()
	endif()
	set(${outvar} "${_archs}" PARENT_SCOPE)
endfunction()

function(semba_fdtd_cuda_default_fat_archs cuda_ver outvar)
	if(cuda_ver VERSION_GREATER_EQUAL 13.0)
		set(${outvar} "75;80;86;89;90;100;120" PARENT_SCOPE)
	elseif(cuda_ver VERSION_GREATER_EQUAL 12.8)
		set(${outvar} "70;75;80;86;89;90;100;120" PARENT_SCOPE)
	elseif(cuda_ver VERSION_GREATER_EQUAL 12.0)
		set(${outvar} "70;75;80;86;89;90" PARENT_SCOPE)
	elseif(cuda_ver VERSION_GREATER_EQUAL 11.8)
		set(${outvar} "70;75;80;86;89;90" PARENT_SCOPE)
	elseif(cuda_ver VERSION_GREATER_EQUAL 11.1)
		set(${outvar} "70;75;80;86" PARENT_SCOPE)
	else()
		set(${outvar} "70;75;80" PARENT_SCOPE)
	endif()
endfunction()

# --- configure-time setup (runs in the including directory) -----------------
if(CMAKE_SCRIPT_MODE_FILE)
	return()
endif()

semba_fdtd_cuda_find_nvcc(_semba_nvcc)
set(CMAKE_CUDA_COMPILER "${_semba_nvcc}" CACHE FILEPATH "NVIDIA CUDA compiler")
set(CMAKE_CUDA_COMPILER "${_semba_nvcc}")
semba_fdtd_cuda_nvcc_version("${CMAKE_CUDA_COMPILER}" _semba_cuda_ver)

semba_fdtd_cuda_pick_host_compiler("${_semba_cuda_ver}" _semba_host)
if(_semba_host)
	set(CMAKE_CUDA_HOST_COMPILER "${_semba_host}" CACHE FILEPATH "CUDA host compiler")
	set(CMAKE_CUDA_HOST_COMPILER "${_semba_host}")
endif()

set(_semba_arch_source)
if(NOT CMAKE_CUDA_ARCHITECTURES)
	if(DEFINED CUDA_ARCH AND NOT CUDA_ARCH STREQUAL "")
		string(REPLACE "sm_" "" _semba_arch "${CUDA_ARCH}")
		string(REPLACE "," ";" _semba_arch "${_semba_arch}")
		string(REPLACE " " "" _semba_arch "${_semba_arch}")
		set(CMAKE_CUDA_ARCHITECTURES "${_semba_arch}" CACHE STRING "CUDA architectures to build for" FORCE)
		set(_semba_arch_source "CUDA_ARCH=${CUDA_ARCH}")
	endif()
endif()

if(NOT CMAKE_CUDA_ARCHITECTURES)
	semba_fdtd_cuda_detect_gpu_archs(_semba_gpu_archs)
	if(_semba_gpu_archs)
		semba_fdtd_cuda_filter_archs("${_semba_gpu_archs}" "${_semba_cuda_ver}" _semba_gpu_archs)
		if(_semba_gpu_archs)
			set(CMAKE_CUDA_ARCHITECTURES "${_semba_gpu_archs}" CACHE STRING "CUDA architectures to build for" FORCE)
			set(_semba_arch_source "nvidia-smi")
		endif()
	endif()
endif()

if(NOT CMAKE_CUDA_ARCHITECTURES)
	if(CMAKE_VERSION VERSION_GREATER_EQUAL 3.23)
		set(CMAKE_CUDA_ARCHITECTURES all-major CACHE STRING "CUDA architectures to build for" FORCE)
		set(_semba_arch_source "all-major")
	else()
		semba_fdtd_cuda_default_fat_archs("${_semba_cuda_ver}" _semba_fat)
		set(CMAKE_CUDA_ARCHITECTURES "${_semba_fat}" CACHE STRING "CUDA architectures to build for" FORCE)
		set(_semba_arch_source "toolkit default")
	endif()
endif()

if(NOT _semba_arch_source)
	set(_semba_arch_source "user/cache")
endif()

semba_fdtd_cuda_filter_archs("${CMAKE_CUDA_ARCHITECTURES}" "${_semba_cuda_ver}" _semba_filtered)
if(NOT _semba_filtered)
	message(FATAL_ERROR
		"No CUDA architecture in '${CMAKE_CUDA_ARCHITECTURES}' is supported by toolkit ${_semba_cuda_ver} "
		"(${CMAKE_CUDA_COMPILER}). Set CMAKE_CUDA_ARCHITECTURES or install a newer toolkit.")
endif()
if(NOT "${_semba_filtered}" STREQUAL "${CMAKE_CUDA_ARCHITECTURES}")
	set(CMAKE_CUDA_ARCHITECTURES "${_semba_filtered}" CACHE STRING "CUDA architectures to build for" FORCE)
endif()

enable_language(CUDA)
find_package(CUDAToolkit REQUIRED)

if(CUDAToolkit_LIBRARY_DIR)
	list(APPEND CMAKE_BUILD_RPATH "${CUDAToolkit_LIBRARY_DIR}")
	list(APPEND CMAKE_INSTALL_RPATH "${CUDAToolkit_LIBRARY_DIR}")
endif()

message(STATUS "FDTD CUDA: nvcc ${CMAKE_CUDA_COMPILER} (toolkit ${CUDAToolkit_VERSION})")
if(CMAKE_CUDA_HOST_COMPILER)
	message(STATUS "FDTD CUDA: host compiler ${CMAKE_CUDA_HOST_COMPILER}")
endif()
message(STATUS "FDTD CUDA: architectures ${CMAKE_CUDA_ARCHITECTURES} (${_semba_arch_source})")
