function(semba_print_configuration_summary)
	message(STATUS "")
	message(STATUS "Solver configuration summary:")
	message(STATUS "  System: ${CMAKE_SYSTEM_NAME}")
	message(STATUS "  Generator: ${CMAKE_GENERATOR}")
	message(STATUS "  Build type: ${CMAKE_BUILD_TYPE}")
	message(STATUS "  Fortran compiler: ${CMAKE_Fortran_COMPILER} (${CMAKE_Fortran_COMPILER_ID} ${CMAKE_Fortran_COMPILER_VERSION})")
	message(STATUS "  C compiler: ${CMAKE_C_COMPILER} (${CMAKE_C_COMPILER_ID} ${CMAKE_C_COMPILER_VERSION})")
	message(STATUS "  Runtime output: ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}")
	message(STATUS "  Library output: ${CMAKE_LIBRARY_OUTPUT_DIRECTORY}")
	message(STATUS "  Fortran modules: ${CMAKE_Fortran_MODULE_DIRECTORY}")
	message(STATUS "  MPI: ${SEMBA_FDTD_ENABLE_MPI}")
	message(STATUS "  HDF5: ${SEMBA_FDTD_ENABLE_HDF}")
	message(STATUS "  MTLN: ${SEMBA_FDTD_ENABLE_MTLN}")
	message(STATUS "  SMBJSON: ${SEMBA_FDTD_ENABLE_SMBJSON}")
	message(STATUS "  Tests: ${SEMBA_FDTD_ENABLE_TEST}")

	if(SEMBA_FDTD_ENABLE_DOUBLE_PRECISION)
		message(STATUS "  Precision: double")
	else()
		message(STATUS "  Precision: single")
	endif()

	if(SEMBA_FDTD_ENABLE_MPI)
		message(STATUS "  MPI Fortran compiler: ${MPI_Fortran_COMPILER}")
		message(STATUS "  MPI version: ${MPI_Fortran_VERSION}")
	endif()

	if(SEMBA_FDTD_ENABLE_HDF)
		message(STATUS "  HDF5 version: ${HDF5_VERSION}")
		message(STATUS "  HDF5 parallel: ${HDF5_IS_PARALLEL}")
		message(STATUS "  HDF5 Fortran libraries: ${HDF5_Fortran_LIBRARIES}")
	endif()

	if(SEMBA_FDTD_ENABLE_MTLN)
		message(STATUS "  LAPACK directory: ${LAPACK_DIR}")
	endif()
endfunction()
